name: Generate Design Tokens With Style Dictionary

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 */4 * * *"

jobs:
  generate_tokens:  
    runs-on: ubuntu-latest
    steps:
    - name: Install Specify CLI
      run: npm install -g @specifyapp/cli
    - name: Pull design data from SPecify
      run: npm run pull-tokens
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'specify'
    - name: Commit Generated Platform Deliverables
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update design tokens
        branch: specify