name: Generate Design Tokens

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 */4 * * *"

jobs:
  generate_tokens:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'specify'
    - name: Install Specify CLI
      run: npm install -g @specifyapp/cli;
    - name: Pull design data from Specify
      run: npm run pull-tokens
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        new_branch: specify
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: specify

    
