name: Update Design Tokens

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 */4 * * *"

jobs:
  update-design-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Specify CLI
        run: npm install -g @specifyapp/cli;
      - name: Pull design data from Specify
        run: |
          specify pull \
            -r @acme-inc/General \
            -C ./.specifyrc/general.js \
            -p ${{ secrets.SPECIFY_TOKEN }};
          specify pull \
            -r @acme-inc/Light-Theme \
            -C ./.specifyrc/light-theme.js \
            -p ${{ secrets.SPECIFY_TOKEN }};
          specify pull \
            -r @acme-inc/Dark-Theme \
            -C ./.specifyrc/dark-theme.js \
            -p ${{ secrets.SPECIFY_TOKEN }};
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update design tokens
          title: 'Update design tokens'
          body: >
            The design tokens and assets contained in this PR come from your [Specify](https://www.specifyapp.com) repositories set in your GitHub Action.
            
            Useful resources:
            - ℹ️ [Documentation](https://specifyapp.com/developers)
            - 🙋 [Help Center](help.specifyapp.com)
            - ⚙️ [Parsers](https://github.com/Specifyapp/parsers/)
            - 👥 [Join our Discord community](https://discord.com/invite/vMkDk4CbG4)

            If you need further assistance feel free to reach out at: [louis@specifyapp.com](mailto:louis@specifyapp.com).
          branch: specify
          labels: Design Tokens